gui_publish_rate: 30.0
kld_err: 0.005
kld_z: 0.99
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_max_beams: 100
laser_max_range: 20.0
laser_min_range: -1.0
laser_model_type: beam
laser_sigma_hit: 0.2
laser_z_hit: 0.5
laser_z_max: 0.05
laser_z_rand: 0.5
laser_z_short: 0.05
max_particles: 2000
min_particles: 200
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1
odom_frame_id: odom
odom_model_type: diff
recovery_alpha_fast: 0.1
recovery_alpha_slow: 0.001
resample_interval: 3
restore_defaults: false
save_pose_rate: 0.5
tf_broadcast: true
transform_tolerance: 0.1
update_min_a: 3.14
update_min_d: 0.2

